apiVersion: apps/v1
kind: Deployment
metadata:
  name: catfact-api
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: catfact-api
  template:
    metadata:
      labels:
        app: catfact-api
    spec:
      containers:
      - name: catfact-api
        image: {{ .Values.image.repository }}:{{ .Values.image.tag }}
        imagePullPolicy: {{ .Values.image.pullPolicy }}
        ports:
        - containerPort: {{ .Values.service.targetPort }}
        resources:
          requests:
            cpu: {{ .Values.resources.requests.cpu }}
            memory: {{ .Values.resources.requests.memory }}
          limits:
            cpu: {{ .Values.resources.limits.cpu }}
            memory: {{ .Values.resources.limits.memory }}
        livenessProbe:
          httpGet:
            path: {{ .Values.probes.liveness.httpGet.path }}
            port: {{ .Values.probes.liveness.httpGet.port }}
          initialDelaySeconds: {{ .Values.probes.liveness.initialDelaySeconds }}
          periodSeconds: {{ .Values.probes.liveness.periodSeconds }}
        readinessProbe:
          httpGet:
            path: {{ .Values.probes.readiness.httpGet.path }}
            port: {{ .Values.probes.readiness.httpGet.port }}
          initialDelaySeconds: {{ .Values.probes.readiness.initialDelaySeconds }}
          periodSeconds: {{ .Values.probes.readiness.periodSeconds }}
