apiVersion: apps/v1
kind: Deployment
metadata:
  name: catfact-api
spec:
  replicas: 1                    #{{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: catfact-api
  template:
    metadata:
      labels:
        app: catfact-api
    spec:
      containers:
      - name: catfact-api
        image: catfact-api                                #"{{ .Values.image.repository }}:{{ .Values.image.tag }}"
        ports:
        - containerPort: 5000
