apiVersion: apps/v1
kind: Deployment
metadata:
  name: catfact-app
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: catfact-app
  template:
    metadata:
      labels:
        app: catfact-app
    spec:
      containers:
      - name: catfact-app
        image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
        ports:
        - containerPort: 5000
