apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: catfact-ingress
spec:
  rules:
    - host: {{ .Values.ingress.host }}
      http:
        paths:
        - path: /catfact
          pathType: Prefix
          backend:
            service:
              name: catfact-api
              port:
                number: {{ .Values.service.port }}
