replicaCount: 1

image:
  repository: catfact-api
  tag: latest
  pullPolicy: Never

service:
  type: ClusterIP
  port: 8080
  targetPort: 5000

ingress:
  enabled: true
  host: catfact-api
  path: /catfact
  pathType: Prefix

container:
  port: 5000

resources:
  requests:
    cpu: "100m"
    memory: "128Mi"
  limits:
    cpu: "500m"
    memory: "256Mi"

probes:
  liveness:
    httpGet:
      path: /health
      port: 5000
    initialDelaySeconds: 5
    periodSeconds: 10
  readiness:
    httpGet:
      path: /health
      port: 5000
    initialDelaySeconds: 3
    periodSeconds: 5