name: CI/CD Pipeline for Cat Fact API

on:
  push:
    branches:
      - main

jobs:
  setup:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Write Kind Configuration
        run: |
          echo "kind: Cluster" > kind-config.yaml
          echo "apiVersion: kind.x-k8s.io/v1alpha4" >> kind-config.yaml
          echo "nodes:" >> kind-config.yaml
          echo "  - role: control-plane" >> kind-config.yaml
          echo "    extraPortMappings:" >> kind-config.yaml
          echo "      - containerPort: 3000" >> kind-config.yaml
          echo "        hostPort: 3000" >> kind-config.yaml
          echo "        protocol: TCP" >> kind-config.yaml

      - name: Set up Kubernetes with Kind
        uses: helm/kind-action@v1.3.0
        with:
          config-path: kind-config.yaml

      - name: Verify Kind Cluster
        run: |
          kubectl cluster-info
          kubectl get nodes

      - name: Install Helm
        uses: azure/setup-helm@v3