name: CI/CD Pipeline for Cat Fact API

on:
  push:
    branches:
      - main

jobs:
  setup:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Write Kind Configuration
        run: |
          cat <<EOF > kind-config.yaml
          kind: Cluster
          apiVersion: kind.x-k8s.io/v1alpha4
          nodes:
            - role: control-plane
              extraPortMappings:
                - containerPort: 3000
                  hostPort: 3000
                  protocol: TCP
          EOF

      - name: Set up Kubernetes with Kind
        uses: helm/kind-action@v1.3.0
        with:
          config-path: kind-config.yaml
          wait: true

      - name: Verify Kind Cluster
        run: |
          kubectl cluster-info
          kubectl get nodes

      - name: Install Helm
        uses: azure/setup-helm@v3