name: CI/CD Pipeline for Cat Fact API

on:
  push:
    branches:
      - main

jobs:
  ci-cd:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout the repository
      - name: Checkout Code
        uses: actions/checkout@v3

      # Step 2: Write Kind Configuration
      - name: Write Kind Configuration
        run: |
          cat <<EOF > kind-config.yaml
          kind: Cluster
          apiVersion: kind.x-k8s.io/v1alpha4
          networking:
            disableDefaultCNI: false
          nodes:
            - role: control-plane
              extraPortMappings:
                - containerPort: 5000
                  hostPort: 2000
                  protocol: TCP
          EOF

      # Step 3: Set up Kubernetes with Kind
      - name: Set up Kubernetes with Kind
        run: |
          kind delete cluster --name kind || true
          kind create cluster --name kind --config=kind-config.yaml

      - name: Remove Taint from Control Plane
        run: |
          kubectl describe node kind | grep Taints
          kubectl taint nodes --all node.kubernetes.io/not-ready-
      
      - name: Wait for Node to be Ready
        run: |
          echo "Waiting for node to be in Ready state..."
          for i in {1..10}; do
            kubectl get nodes | grep -q ' Ready ' && break
            echo "Node not ready yet. Retrying in 10s..."
            sleep 10
          done
          kubectl get nodes

      # Step 4: Set Kubernetes Context
      - name: Set Kubernetes Context
        run: |
          kubectl config use-context kind-kind

      # Step 5: Install Helm
      - name: Install Helm
        uses: azure/setup-helm@v3

      # Step 6: Add pre-steps for linting
      - name: Lint Helm Charts
        run: helm lint ./charts

      # Step 7: Build Docker Image
      - name: Build Docker Image
        run: |
          docker build -t catfact-api .

      # Step 8: Load Docker Image into Kind
      - name: Load Docker Image into Kind
        run: |
          kind load docker-image catfact-api --name kind

      # Step 9: Deploy Application using Helm
      - name: Deploy Application using Helm
        run: |
          helm upgrade --install catfact-api ./charts 

      # Step 10: Replace sleep with dynamic pod readiness check
      - name: Wait for Pods to be Ready
        run: |
          kubectl wait --for=condition=ready pod --all --timeout=120s

      # Step 11: Install Curl
      - name: Install Curl
        run: sudo apt-get install -y curl

      # Step 12: Test Endpoints
      - name: Test Endpoints
        run: |
      
          #kubectl port-forward service/catfact-api 8080:8080 &
          #sleep 10

          # Test /catfact endpoint
          echo "Testing /catfact endpoint..."
          curl -s http://localhost:2000/catfact

          # Test /health endpoint
          echo "Testing /health endpoint..."
          curl -s http://localhost:2000/health

      # Step 13: Clean up resources
      - name: Clean Up Kind Cluster
        run: kind delete cluster --name kind
